spring:
  application:
    name: ms-naissances
  datasource:
    username: root
    password: Mfoulou237@
    url: jdbc:mysql://localhost:3306/db_naissance
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /api
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    org.springframework.security: trace